### ISSUE TITLE
[BUG] compilation error when running `deepseekv32/sparse_mla_fwd.py` under cuda12.1

### ISSUE THREAD

**Issue by GoldenStain** [tile-ai/tilelang#1564]
### Required prerequisites

- [x] I have read the documentation <https://tilelang.com>.
- [x] I have searched the [Issue Tracker](https://github.com/tile-ai/tilelang/issues) that this hasn't already been reported. (comment there if it has.)

### What version of TileLang are you using?

0.1.7.post1

### System information

- installed by pip.
- python: 3.9.12
- cuda ver: 12.1
- torch ver: 2.8.0+cu128
- platform: linux

### Problem description

Encountered compilation error `identifier "__nv_fp8_e8m0" is undefined` when running `examples/deepseekv32/sparse_mla_fwd.py`

### Reproducible example code

The Python snippets:

```python
python -m examples.deepseekv32.sparse_mla_fwd
```

### Traceback

```pytb
identifier "__nv_fp8_e8m0" is undefined
```

### Expected behavior

Run successfully.

### Additional context

To my knowledge, __nv_fp8_e8m0 was introduced in cuda11.8, but it's not visible in cuda12.1, should tilelang replace it with other types when it's not available?

**Comment by LeiWang1999** [comment]
@GoldenStain Thanks for your report, would you mind checkout the main branch and have a try?

**Comment by GoldenStain** [comment]
> [@GoldenStain](https://github.com/GoldenStain) Thanks for your report, would you mind checkout the main branch and have a try?

Copy that, I'll try it later.

**Comment by GoldenStain** [comment]
The issue is fixed on the main branch.

**Comment by DB-Guo** [comment]
@LeiWang1999 
Same bug in cuda12.6 on L20 when running examples/gemm/example_gemm_persistent.py
It seems that __nv_fp8_e8m0 is not available in cuda12.6 either. but it is available in cuda 12.8
ref: https://docs.nvidia.com/cuda/archive/12.6.3/cuda-math-api/cuda_math_api/structs.html
https://docs.nvidia.com/cuda/archive/12.8.0/cuda-math-api/cuda_math_api/structs.html

**Comment by Imke7** [comment]
@LeiWang1999 
I encountered a similar issue with CUDA 12.6 and TileLang 0.1.7.post3 when I tried to run the minimal end-to-end vector add example from the documentation (https://tilelang.com/programming_guides/language_basics.html#a-minimal-endtoend-example-vector-add). 

I am using Python 3.12.12. This is the error that I get: 
```
tilelang/3rdparty/../src/tl_templates/cuda/cuda_fp8.h(13) error: identifier "__nv_fp8_e8m0" is undefined
  using fp8_e8_t = __nv_fp8_e8m0;
```

I tried the main branch as suggested, but the problem persists. I tried downgrading TileLang to version 0.1.6 and that fixed the issue for me.

**Comment by GoldenStain** [comment]
> [@LeiWang1999](https://github.com/LeiWang1999) I encountered a similar issue with CUDA 12.6 and TileLang 0.1.7.post3 when I tried to run the minimal end-to-end vector add example from the documentation (https://tilelang.com/programming_guides/language_basics.html#a-minimal-endtoend-example-vector-add).
> 
> I am using Python 3.12.12. This is the error that I get:
> 
> ```
> tilelang/3rdparty/../src/tl_templates/cuda/cuda_fp8.h(13) error: identifier "__nv_fp8_e8m0" is undefined
>   using fp8_e8_t = __nv_fp8_e8m0;
> ```
> 
> I tried the main branch as suggested, but the problem persists. I tried downgrading TileLang to version 0.1.6 and that fixed the issue for me.

It may have to do with CUDA version.

**Comment by Puiching-Memory** [comment]
Thanks for discussing this. I ran into the same problem independently while bringing up a first TileLang operator locally, so I wanted to add one external data point.

From the history side, the current CUDA-version guard around this path seems to come from [d219f6c](https://github.com/tile-ai/tilelang/commit/d219f6c9832656be2818f3a87947c7c64080f36e), while the underlying fp8_e8_t = __nv_fp8_e8m0 alias appears to have been introduced earlier in [dda4512](https://github.com/tile-ai/tilelang/commit/dda451269c6dfea7fdc7f2fede8e86b2b5621819).

On my side, I was testing a float16 RMSNorm kernel on an NVIDIA H800 machine with CUDA 12.6 and TileLang 0.1.9. After fixing a couple of unrelated local bring-up issues first, such as JIT source inspection and Python annotation handling, TileLang was able to reach real NVCC compilation. At that point, the remaining stable failure was consistently:

identifier "__nv_fp8_e8m0" is undefined

coming from TileLang's cuda_fp8.h.

To narrow this down, I checked the local CUDA 12.6 headers directly and could not find __nv_fp8_e8m0 or the related __nv_cvt_*e8m0* APIs in cuda_fp8.h / cuda_fp8.hpp.

I also cross-checked the public CUDA Math API documentation:

- [CUDA 11.8 FP8 docs](https://docs.nvidia.com/cuda/archive/11.8.0/cuda-math-api/group__CUDA__MATH__INTRINSIC__FP8.html) already document FP8 support, but only for e4m3 and e5m2
- [CUDA 12.1 FP8 docs](https://docs.nvidia.com/cuda/archive/12.1.0/cuda-math-api/group__CUDA__MATH__INTRINSIC__FP8.html) still show e4m3 and e5m2, but I could not find __nv_fp8_e8m0 there either
- [CUDA 12.6.3 structs](https://docs.nvidia.com/cuda/archive/12.6.3/cuda-math-api/cuda_math_api/structs.html) still do not list __nv_fp8_e8m0
- [CUDA 12.8.0 structs](https://docs.nvidia.com/cuda/archive/12.8.0/cuda-math-api/cuda_math_api/structs.html) and the dedicated [__nv_fp8_e8m0 page](https://docs.nvidia.com/cuda/archive/12.8.0/cuda-math-api/cuda_math_api/struct____nv__fp8__e8m0.html) do list it explicitly

So my current understanding is that there is a distinction between “public FP8 support in general” and the specific __nv_fp8_e8m0 type. CUDA 11.8 does seem to introduce public FP8 support, but based on the public headers and docs I checked, I could not verify that __nv_fp8_e8m0 itself is available in 11.8, 12.1, 12.5, or 12.6. The earliest public CUDA version I could verify that explicitly documents __nv_fp8_e8m0 is 12.8.0.

As a local experiment, I disabled the E8M0 branch in the installed TileLang cuda_fp8.h while keeping the rest of the environment unchanged, and the exact same float16 RMSNorm benchmark then compiled and ran successfully on the same CUDA 12.6 machine.

So from this external reproduction, this looks less like an operator-specific bug and more like the current guard may be enabling the E8M0 path based only on CUDA version, even when the installed CUDA headers do not actually expose those symbols. If that reading is correct, it may be safer to gate this on actual symbol/header availability rather than only on CUDA version.
